declare const DECA: number;
declare const HECTO: number;
declare const KILO: number;
declare const MEGA: number;
declare const GIGA: number;
declare const TERA: number;
declare const PETA: number;
declare const EXA: number;
declare const ZETA: number;
declare const YOTTA: number;
declare const DECI: number;
declare const CENTI: number;
declare const MILI: number;
declare const MICRO: number;
declare const NANO: number;
declare const PICO: number;
declare const FEMTO: number;
declare const ATTO: number;
declare const ZEPTO: number;
declare const YOCTO: number;
declare const GRAU: number;
declare const MILHA = 1609.344;
declare const MILHA_NAUTICA = 1852;
declare const POLEGADA = 0.3048;
declare const PE = 0.3048;
declare const JARDAS = 0.9144;
declare const PALMO: number;
declare const BRACA: number;
declare const VARA: number;
declare const CORRENTE: number;
declare const FURLONG = 201.168;
declare const ROD: number;
declare const ANOS_LUZ = 9460730472580800;
declare const PARSEC = 30856775800000000;
declare const UNIDADADE_ASTRONOMICA = 149597870691;
declare const ANGSTROM = 1e-10;
declare const ACRE = 4046.86;
declare const ARE = 100;
declare const HECTARE = 10000;
declare const ALQUEIRE: number;
declare const DUNAM: number;
declare const ROOD: number;
declare const HOMESTEAD: number;
declare const LITRO = 0.001;
declare const DECILITRO = 0.01;
declare const CENTILITRO = 0.1;
declare const MILILITRO = 1;
declare const MICROLITRO: number;
declare const NANOLITRO: number;
declare const PICOLITRO: number;
declare const FEMTOLITRO: number;
declare const ATOLITRO: number;
declare const ZEPTOLITRO: number;
declare const YOTTOLITRO: number;
declare const DECALITRO: number;
declare const HECTOLITRO: number;
declare const KILOLITRO: number;
declare const MEGALITRO: number;
declare const GIGALITRO: number;
declare const TERALITRO: number;
declare const PETALITRO: number;
declare const EXALITRO: number;
declare const ZETALITRO: number;
declare const YOTALITRO: number;
declare const JARDALITRO = 0.9144;
declare const PINTADO = 0.473176473;
declare const TONEL = 0.000001;
declare const PIPA = 0.000001;
declare const ALMUDE = 1;
declare const ALMUDE_ARABE = 1;
declare const ALMUDE_CONDADO_PORTUCALENSE = 1;
declare const ALMUDE_CONDADO_DOM_AFONSO_HENRIQUES = 1;
declare const ALMUDE_DOM_PEDRO_I = 1;
declare const ALMUDE_DOM_PEDRO_II = 1;
declare const ALMUDE_DOM_MANUEL_I = 1;
declare const ALMUDE_CONSELHO_SANTO_TIRSO_RIO_AVE = 1;
declare const ALMUDE_CONSELHO_SANTO_TIRSOpVALE_DO_LECA = 1;
declare const ALMUDE_COIMBRA_VINHO = 1;
declare const ALMUDE_COIMBRA_AZEITE = 1;
declare const GALAO = 0.00378541;
declare const GALAO_LIQUIDO = 0.00378541;
declare const GALAO_LIQUIDO_BARRIS_ESTADUNIDENSES = 0.00378541;
declare const GALAO_LIQUIDO_QUARTOS_ESTADUNIDENSES = 0.00378541;
declare const GALAO_LIQUIDO_QUARTILHOS_ESTADUNIDENSES = 0.00378541;
declare const GALAO_LIQUIDO_GILLS_ESTADUNIDENSES = 0.00378541;
declare const GALAO_LIQUIDO_ONCAS_ESTADUNIDENSES = 0.00378541;
declare const GALAO_SECO = 0.00378541;
declare const GALAO_SECO_QUARTILHOS = 0.00378541;
declare const GALAO_SECO_QUARTOS = 0.00378541;
declare const GALAO_SECO_PECKS = 0.00378541;
declare const GALAO_SECO_BUSHELS = 0.00378541;
declare const GALAO_IMPERIAL = 0.00378541;
declare const GALAO_IMPERIAL_BARRIS_BRITANICOS = 0.00378541;
declare const GALAO_IMPERIAL_QUARTOS_BRITANICOS = 0.00378541;
declare const GALAO_IMPERIAL_QUARTILHOS_BRITANICOS = 0.00378541;
declare const GALAO_IMPERIAL_GILLS_BRITANICOS = 0.00378541;
declare const GALAO_IMPERIAL_ONCAS_BRITANICOS = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO_BARRIS_IMPERIAIS = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO_GALOES_IMPERIAIS = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO_PINTOS_IMPERIAIS = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO_GILLS_IMPERIAIS = 0.00378541;
declare const QUARTO_IMPERIAL_BRITANICO_ONCAS_LIQUIDAS_IMPERIAIS = 0.00378541;
declare const QUARTO_ESTADUNIDENSE = 0.00378541;
declare const QUARTO_ESTADUNIDENSE_BARRIS_ESTADUNIDENSES = 0.00378541;
declare const QUARTO_ESTADUNIDENSE_GALOES_ESTADUNIDENSES = 0.00378541;
declare const QUARTO_ESTADUNIDENSE_PINTOS_ESTADUNIDENSES = 0.00378541;
declare const QUARTO_ESTADUNIDENSE_GILLS_ESTADUNIDENSES = 0.00378541;
declare const QUARTO_ESTADUNIDENSE_ONCAS_LIQUIDAS_ESTADUNIDENSES = 0.00378541;
declare const PINTO_BRITANICO = 0.00378541;
declare const PINTO_ESTADOS_UNIDOS = 0.00378541;
declare const PINTO_AUSTRALIA = 0.00378541;
declare const PINTO_CANADENSE = 0.00378541;
declare const PINTO_FRANCES = 0.00378541;
declare const PINTO_BELGICA = 0.00378541;
declare const PINTO_BRITANICO_BARRIS_IMPERIAIS = 0.00378541;
declare const PINTO_BRITANICO_GALOES_IMPERIAIS = 0.00378541;
declare const PINTO_BRITANICO_GILLS_IMPERIAIS = 0.00378541;
declare const PINTO_BRITANICO_ONCAS_LIQUIDAS_IMPERIAIS = 0.00378541;
declare const PINTO_BRITANICO_BARRIS_ESTADUNIDENSES = 0.00378541;
declare const PINTO_BRITANICO_GALOES_ESTADUNIDENSES = 0.00378541;
declare const PINTO_BRITANICO_GILLS_ESTADUNIDENSES = 0.00378541;
declare const PINTO_BRITANICO_ONCAS_LIQUIDAS_ESTADUNIDENSES = 0.00378541;
declare const QUINTAL_PORTUGUES = 1;
declare const QUINTAL_DE_PESO_GRANDE = 1;
declare const QUINTAL_DE_PESO_PEQUENO = 1;
declare const QUINTAL_METRICO = 1;
declare const QUINTAL_METRICO_GRAMAS = 1;
declare const QUINTAL_METRICO_DECAGRAMAS = 1;
declare const QUINTAL_METRICO_HECTOGRAMAS = 1;
declare const QUINTAL_METRICO_KILOGRAMAS = 1;
declare const QUINTAL_METRICO_MINIAGRAMAS = 1;
declare const QUINTAL_METRICO_TONELADAS_METRICAS = 1;
declare const QUINTAL_METRICO_TONELADAS = 1;
declare const QUINTAL_NORTE_AMERICANO = 1;
declare const QUINTAL_NORTE_AMERICANO_GRAOS = 1;
declare const QUINTAL_NORTE_AMERICANO_DACMAS_AVOIRDUPOIS = 1;
declare const QUINTAL_NORTE_AMERICANO_ONCAS_AVOIRDUPOIS = 1;
declare const QUINTAL_NORTE_AMERICANO_LIBRAS_AVOIRDUPOIS = 1;
declare const QUINTAL_NORTE_AMERICANO_ARROBAS = 1;
declare const QUINTAL_NORTE_AMERICANO_QUARTOS_CURTOS = 1;
declare const QUINTAL_NORTE_AMERICANO_TONELADAS_CURTAS = 1;
declare const QUINTAL_BRITANICO = 1;
declare const QUINTAL_BRITANICO_GRAOS = 1;
declare const QUINTAL_BRITANICO_DACMAS_AVOIRDUPOIS = 1;
declare const QUINTAL_BRITANICO_ONCAS_AVOIRDUPOIS = 1;
declare const QUINTAL_BRITANICO_LIBRAS_AVOIRDUPOIS = 1;
declare const QUINTAL_BRITANICO_STONES = 1;
declare const QUINTAL_BRITANICO_QUARTOS_CURTOS = 1;
declare const QUINTAL_BRITANICO_TONELADAS_CURTAS = 1;
declare const SESTEIRO = 1;
declare const SESTEIRO_MOIO = 1;
declare const SESTEIRO_SEC_XI = 1;
declare const SESTEIRO_SEC_XIV = 1;
declare const SESTEIRO_CONGIUS = 1;
declare const SESTEIRO_MODIUS = 1;
declare const SESTEIRO_SEXTANS = 1;
declare const SESTEIRO_TRIENS = 1;
declare const SESTEIRO_HEMINA = 1;
declare const SESTEIRO_CHOENIX = 1;
declare const ARRATEL = 1;
declare const ONCA = 1;
declare const TONELADA = 1000;
declare const DUZIA = 12;
declare const GROSA = 6;
declare const ATM = 101325;
declare const TORR = 133.322;
declare const BEL = 1;
declare const DECIBEL = 0.1;
declare const CANDELA = 1;
declare const LUMEN_QUADRADO = 1;
declare const LUMEN_SEGUNDO = 1;
declare const LUX_QUADRADO = 1;
declare const LUX_SEGUNDO = 1;
declare const LUMEN_WATT = 1;
declare const LUX_WATT = 1;
declare const LUMEN_CUBICO = 1;
declare const LUX_CUBICO = 1;
declare const CALORIA = 4.184;
declare const KILOCALORIA = 4184;
//# sourceMappingURL=conversores-variaveis.d.ts.map