export declare function $exponencial(n1: number): number;
export declare function $exponencialMenosUm(n1: number): number;
export declare function $exponencialInversa(n1: number): number;
export declare function $exponencialInversaMenosUm(n1: number): number;
export declare function $exponencialHiperbolica(n1: number): number;
export declare function $exponencialHiperbolicaMenosUm(n1: number): number;
export declare function $exponencialHiperbolicaInversa(n1: number): number;
export declare function $exponencialHiperbolicaInversaMenosUm(n1: number): number;
export declare function $logaritmoNatural(x1: number): number;
export declare function $logaritmoNaturalMaisUm(x1: number): number;
export declare function $logaritmoBase10(x1: number): number;
export declare function $logaritmoBase2(x1: number): number;
export declare function $logaritmoBaseQualquer(x1: number, x2: number): number;
export declare function $logaritmoBaseQualquerMenosUm(x1: number, x2: number): number;
export declare function $logaritmoNaturalInverso(x1: number): number;
export declare function $logaritmoNaturalInversoMaisUm(x1: number): number;
export declare function $logaritmoBase10Inverso(x1: number): number;
export declare function $logaritmoBase2Inverso(x1: number): number;
export declare function $logaritmoBaseQualquerInverso(x1: number, x2: number): number;
export declare function $logaritmoBaseQualquerInversoMenosUm(x1: number, x2: number): number;
export declare function $logaritmoNaturalHiperbolico(x1: number): number;
export declare function $logaritmoNaturalHiperbolicoMaisUm(x1: number): number;
export declare function $logaritmoBase10Hiperbolico(x1: number): number;
export declare function $logaritmoBase2Hiperbolico(x1: number): number;
export declare function $logaritmoBaseQualquerHiperbolico(x1: number, x2: number): number;
export declare function $logaritmoBaseQualquerHiperbolicoMenosUm(x1: number, x2: number): number;
export declare function $logaritmoNaturalInversoHiperbolico(x1: number): number;
export declare function $logaritmoNaturalInversoHiperbolicoMaisUm(x1: number): number;
export declare function $logaritmoBase10InversoHiperbolico(x1: number): number;
export declare function $logaritmoBase2InversoHiperbolico(x1: number): number;
export declare function $logaritmoBaseQualquerInversoHiperbolico(x1: number, x2: number): number;
export declare function $logaritmoBaseQualquerInversoHiperbolicoMenosUm(x1: number, x2: number): number;
export declare function $antilogaritmoNatural(x1: number): number;
export declare function $antilogaritmoNaturalMaisUm(x1: number): number;
export declare function $antilogaritmoBase10(x1: number): number;
export declare function $antilogaritmoBase2(x1: number): number;
export declare function $antilogaritmoBaseQualquer(x1: number, x2: number): number;
export declare function $antilogaritmoBaseQualquerMenosUm(x1: number, x2: number): number;
export declare function $antilogaritmoNaturalInverso(x1: number): number;
export declare function $antilogaritmoNaturalInversoMaisUm(x1: number): number;
export declare function $antilogaritmoBase10Inverso(x1: number): number;
export declare function $antilogaritmoBase2Inverso(x1: number): number;
export declare function $antilogaritmoBaseQualquerInverso(x1: number, x2: number): number;
export declare function $antilogaritmoBaseQualquerInversoMenosUm(x1: number, x2: number): number;
export declare function $antilogaritmoNaturalHiperbolico(x1: number): number;
export declare function $antilogaritmoNaturalHiperbolicoMaisUm(x1: number): number;
export declare function $antilogaritmoBase10Hiperbolico(x1: number): number;
export declare function $antilogaritmoBase2Hiperbolico(x1: number): number;
export declare function $antilogaritmoBaseQualquerHiperbolico(x1: number, x2: number): number;
export declare function $antilogaritmoBaseQualquerHiperbolicoMenosUm(x1: number, x2: number): number;
export declare function $antilogaritmoNaturalInversoHiperbolico(x1: number): number;
export declare function $antilogaritmoNaturalInversoHiperbolicoMaisUm(x1: number): number;
export declare function $antilogaritmoBase10InversoHiperbolico(x1: number): number;
export declare function $antilogaritmoBase2InversoHiperbolico(x1: number): number;
export declare function $antilogaritmoBaseQualquerInversoHiperbolico(x1: number, x2: number): number;
export declare function $antilogaritmoBaseQualquerInversoHiperbolicoMenosUm(x1: number, x2: number): number;
export declare function $cologaritmoNatural(x1: number): number;
export declare function $cologaritmoNaturalMaisUm(x1: number): number;
export declare function $cologaritmoBase10(x1: number): number;
export declare function $cologaritmoBase2(x1: number): number;
export declare function $cologaritmoBaseQualquer(x1: number, x2: number): number;
export declare function $cologaritmoBaseQualquerMaisUm(x1: number, x2: number): number;
export declare function $cologaritmoNaturalInverso(x1: number): number;
export declare function $cologaritmoNaturalInversoMaisUm(x1: number): number;
export declare function $cologaritmoBase10Inverso(x1: number): number;
export declare function $cologaritmoBase2Inverso(x1: number): number;
export declare function $cologaritmoBaseQualquerInverso(x1: number, x2: number): number;
export declare function $cologaritmoBaseQualquerInversoMaisUm(x1: number, x2: number): number;
export declare function $cologaritmoNaturalHiperbolico(x1: number): number;
export declare function $cologaritmoNaturalHiperbolicoMaisUm(x1: number): number;
export declare function $cologaritmoBase10Hiperbolico(x1: number): number;
export declare function $cologaritmoBase2Hiperbolico(x1: number): number;
export declare function $cologaritmoBaseQualquerHiperbolico(x1: number, x2: number): number;
export declare function $cologaritmoBaseQualquerHiperbolicoMaisUm(x1: number, x2: number): number;
export declare function $cologaritmoNaturalInversoHiperbolico(x1: number): number;
export declare function $cologaritmoNaturalInversoHiperbolicoMaisUm(x1: number): number;
export declare function $cologaritmoBase10InversoHiperbolico(x1: number): number;
export declare function $cologaritmoBase2InversoHiperbolico(x1: number): number;
export declare function $cologaritmoBaseQualquerInversoHiperbolico(x1: number, x2: number): number;
export declare function $cologaritmoBaseQualquerInversoHiperbolicoMaisUm(x1: number, x2: number): number;
//# sourceMappingURL=funcoes-cientificas-avancadas.d.ts.map