export declare function $areaTrianguloQualquer(lado: any): number;
export declare function $apotemaDeUmTrianguloQualquer(lado: any): number;
export declare function $areaQuadradoQualquer(lado: number): number;
export declare function $areaRetanguloQualquer(comp: number, larg: number): number;
export declare function $areaCirculoQualquer(raio: number): number;
export declare function $areaElipseQualquer(raio: number, altura: number): number;
export declare function $areaPiramideQualquer(base: number, altura: number): number;
export declare function $areaTrapezioQualquer(baseMaior: number, baseMenor: number, altura: number): number;
export declare function $areaLozangoQualquer(diagonalMaior: number, diagonalMenor: number, altura: number): number;
export declare function $areaDeUmaSuperficieQualquer(comp: number, larg: number): number;
export declare function $volumeDeUmaSuperficieQualquer(area: number, comp: number, larg: number): number;
export declare function $areaEsferaQualquer(raio: number): number;
export declare function $areaCilindroQualquer(raio: number, altura: number): number;
export declare function $areaConeQualquer(raio: number, altura: number): number;
export declare function $areaDeUmPoligonoQualquer(comp: number, larg: number, nLados: number): number;
export declare function $volumeDeUmPoligonoFormatoLozangoQualquer(diagonalMaior: number, diagonalMenor: number, altura: number): number;
export declare function $volumeDeUmPoligonoFormatoTrapezioQualquer(baseMaior: number, baseMenor: number, altura: number): number;
export declare function $areaDeUmParalelogramoQualquer(lado: number, altura: number): number;
export declare function $areaLateralDeUmPrismaQualquer(comp: number, larg: number, nLados: number): number;
export declare function $volumeDeUmPrismaQualquer(area: number, comp: number, larg: number): number;
export declare function $volumeDeUmCuboQualquer(aresta: number): number;
export declare function $volumeDeUmParalelepipedoQualquer(comprimento: number, largura: number, altura: number): number;
export declare function $volumeDeUmPiramideQualquer(base: number, altura: number): number;
export declare function $volumeDeUmTetraedroQualquer(aresta: number): number;
export declare function $volumeDeUmHexaedroQualquer(aresta: number): number;
export declare function $volumeDeUmOctaedroQualquer(aresta: number): number;
export declare function $volumeDeUmDodecaedroQualquer(aresta: number): number;
export declare function $volumeDeUmIcosaedroQualquer(aresta: number): number;
export declare function $volumeDeUmConeQualquer(raio: number, altura: number): number;
export declare function $volumeDeUmCilindroQualquer(raio: number, altura: number): number;
export declare function $volumeDeUmEsferaQualquer(raio: number): number;
export declare function $volumeDeUmRombQualquer(aresta: number): number;
export declare function $areaCircunferenciaQualquer(raio: number): number;
//# sourceMappingURL=funcoes-geometricas.d.ts.map