
// &          canvas
// &          noscript
// &          script
// &          del
// &          ins
// &          caption
// &          col
// &          colgroup
// &          table
// &          tbody
// &          td
// &          tfoot
// &          th
// &          thead
// &          tr
// &          button
// &          datalist
// &          fieldset
// &          form
// &          input
// &          label
// &          legend
// &          meter
// &          optgroup
// &          option
// &          output
// &          progress
// &          select
// &          textarea
// &          details
// &          dialog
// &          menu
// &          summary
// &          content
// &          shadow
// &          slot
// &          template
// &          acronym
// &          appconst
// &          basefont
// &          bgsound
// &          big
// &          blink
// &          center
// &          dir
// &          font
// &          frame
// &          frameset
// &          hgroup
// &          image
// &          keygen
// &          marquee
// &          menuitem
// &          nobr
// &          noembed
// &          noframes
// &          plaintext
// &          rb
// &          rtc
// &          spacer
// &          strike
// &          tt
// &          xmp