main:
	g++ wtsfy.cpp -o out/wtsfy.exe -std=c++23

exec: main
	./out/wtsfy.exe

# variaveis de flags do gpp
# -Wall: mostra todos os warnings
# -Wextra: mostra mais warnings
# -Wpedantic: mostra mais warnings
# -Werror: transforma todos os warnings em erros
# -std=c++23: define a versão do c++ para c++23
# -O3: otimizações de compilação
# -g: gera informações de debug
# -fsanitize=address: habilita o address sanitizer
# -fsanitize=leak: habilita o leak sanitizer
# -fsanitize=undefined: habilita o undefined sanitizer
# -fsanitize=thread: habilita o thread sanitizer
# -fsanitize=memory: habilita o memory sanitizer
# -fno-omit-frame-pointer: desabilita a otimização do frame pointer
# -fno-optimize-sibling-calls: desabilita a otimização de chamadas de funções irmãs
# -fno-inline: desabilita a otimização de inline
