# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "labo@reunion-pieces" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # You may pin to the exact commit or the version.
      # uses: saadmk11/changelog-ci@94435ac02b50745a2543caf0c5d6eae23665615a
      - uses: saadmk11/changelog-ci@v1.1.2
        # with:
          # Name of the changelog file if not provided defaults to CHANGELOG.md
          # changelog_filename: # optional, default is CHANGELOG.md
          # Location of the config JSON file
          # config_file: # optional
          # Name of the user who will commit the changes to GitHub
          # committer_username: # optional, default is github-actions[bot]
          # Email Address of the user who will commit the changes to GitHub
          # committer_email: # optional, default is github-actions[bot]@users.noreply.github.com
          # The release version that will be used on the generated Changelog
          # release_version: # optional
          # GITHUB_TOKEN or Personal Access Token (PAT)
          # github_token: # optional, default is ${{ github.token }}
            
