name: Workflow

on: 
  push:
    branches: [ main, version-2.0.0 ]
  pull_request:
    branches: [ main, version-2.0.0 ]

jobs:
  # ESLint Report Action 
  # (https://github.com/marketplace/actions/eslint-report)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo checkout 
        uses: actions/checkout@v3
      
      - name: Configurando NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Rodando integração de código
        run: npm ci
      
      - name: Rodando verificador de falhas de código e exportando em um JSON
        run: npm run lint:json
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install
      - run: yarn lint
      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: eslint

      - run: yarn test
